### ISSUE TITLE
Scripts to run robot localization experiments (section 5.3) 

### ISSUE THREAD

**Issue by vmasrani** [JTT94/filterflow#17]
I'm currently trying to reproduce the robot localization experiment in section 5.3 of [Differentiable Particle Filtering via Entropy-Regularized Optimal Transport](https://arxiv.org/abs/2102.07850), but I can't seem to find the appropriate script in [filterflow/scripts](https://github.com/JTT94/filterflow/tree/master/scripts). Could you point me in the right direction?  Thanks for the excellent package!

**Comment by AdrienCorenflos** [comment]
Hi,

This bit ended up being coded in pytorch, @JTT94 must have forgotten to make the repo public.

Adrien

**Comment by JTT94** [comment]
Yes it will be made available. Currently being adapted for other projects.
