### ISSUE TITLE
PyTorch Implementation

### ISSUE THREAD

**Issue by qshzh** [JTT94/filterflow#18]
The paper mentions the PyTorch implementation is also available. Also based on the [issue](https://github.com/JTT94/filterflow/issues/17#issue-892769181), some experiments are based on PyTorch implementation. 

Is there any plan for making the implementation public?

**Comment by JTT94** [comment]
Yes it will be made available. Currently being adapted for other projects.

**Comment by xiongjiechen** [comment]
Hi James,

Any update on the PyTorch implementation of the robot tracking experiment? Thanks!

**Comment by sustcsonglin** [comment]
Waiting for the Pytorch implementation
